"""Getting text into the app you were dictating into.

This module exists because the naive version — pbcopy, osascript ⌘V, sleep,
pbcopy back — fails in at least six ways that all look like success:

  * `osascript`'s exit code was captured and discarded, so a revoked
    Accessibility permission produced a "✓ pasted" message and no text.
  * `pbpaste`/`pbcopy` cannot round-trip a pasteboard. Copy a screenshot,
    dictate, and the screenshot is gone — replaced by an empty string.
  * The restore ran after a fixed 200ms guess. Under the CPU pressure that
    immediately follows a Whisper decode, Electron apps routinely miss it, so
    the *old* clipboard gets pasted instead of the transcript.
  * If a trigger key was still physically held, the synthesised ⌘V became
    ⌥⌘V — "Paste and Match Style" in most apps, and "Move Item Here" in
    Finder, which relocates files.
  * macOS Secure Input Mode (active whenever any password field has focus)
    silently discards synthetic keystrokes.
  * Two overlapping dictations interleaved their save/restore and destroyed
    the clipboard.

Everything here is serialised on one lock, verified where verification is
possible, and loud when it is not.
"""
from __future__ import annotations

import subprocess
import threading
import time

_PASTE_LOCK = threading.Lock()

# Pasteboard types we deliberately skip when snapshotting: transient, huge, or
# regenerated by the source app anyway.
_SKIP_TYPES = {"com.apple.pasteboard.promised-file-url"}


class PasteResult:
    def __init__(self, ok: bool, method: str, detail: str = ""):
        self.ok = ok
        self.method = method
        self.detail = detail

    def __repr__(self) -> str:
        return f"PasteResult(ok={self.ok}, method={self.method!r}, detail={self.detail!r})"


# ──────────────────────────────────────────────────────────────
# Clipboard
# ──────────────────────────────────────────────────────────────
def _pasteboard():
    from AppKit import NSPasteboard
    return NSPasteboard.generalPasteboard()


def snapshot_clipboard() -> list[tuple[str, bytes]] | None:
    """Capture every flavour on the pasteboard, not just plain text.

    Returns a list of (type, data) or None if the pasteboard can't be read.
    Using NSPasteboard rather than `pbpaste` is what makes an image, a file
    reference or styled text survive a dictation.
    """
    try:
        pb = _pasteboard()
        items = []
        types = pb.types() or []
        for t in types:
            t = str(t)
            if t in _SKIP_TYPES:
                continue
            data = pb.dataForType_(t)
            if data is not None:
                items.append((t, bytes(data)))
        return items
    except Exception:
        return None


def restore_clipboard(items: list[tuple[str, bytes]] | None) -> bool:
    if items is None:
        return False
    try:
        from Foundation import NSData
        pb = _pasteboard()
        pb.clearContents()
        pb.declareTypes_owner_([t for t, _ in items], None)
        for t, data in items:
            pb.setData_forType_(NSData.dataWithBytes_length_(data, len(data)), t)
        return True
    except Exception:
        return False


def set_clipboard(text: str) -> bool:
    try:
        from AppKit import NSPasteboard, NSPasteboardTypeString
        pb = NSPasteboard.generalPasteboard()
        pb.clearContents()
        return bool(pb.setString_forType_(text, NSPasteboardTypeString))
    except Exception:
        try:
            subprocess.run(["pbcopy"], input=text, text=True, check=True)
            return True
        except Exception:
            return False


def get_clipboard_text() -> str:
    try:
        from AppKit import NSPasteboard, NSPasteboardTypeString
        return NSPasteboard.generalPasteboard().stringForType_(NSPasteboardTypeString) or ""
    except Exception:
        return ""


# ──────────────────────────────────────────────────────────────
# Keystroke safety
# ──────────────────────────────────────────────────────────────
def held_modifiers() -> set[str]:
    """Modifier keys physically down right now.

    Matters because dictation #2's key is often still held while dictation
    #1's paste fires. ⌥ held turns ⌘V into ⌥⌘V — "Move Item Here" in Finder.
    """
    try:
        import Quartz
        flags = Quartz.CGEventSourceFlagsState(
            Quartz.kCGEventSourceStateCombinedSessionState)
        out = set()
        if flags & Quartz.kCGEventFlagMaskCommand:   out.add("cmd")
        if flags & Quartz.kCGEventFlagMaskAlternate: out.add("alt")
        if flags & Quartz.kCGEventFlagMaskControl:   out.add("ctrl")
        if flags & Quartz.kCGEventFlagMaskShift:     out.add("shift")
        return out
    except Exception:
        return set()


def wait_for_modifiers_released(timeout: float = 2.0) -> bool:
    """Block until ⌥/⌃/⇧ are up, so the synthetic ⌘V isn't modified."""
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        if not (held_modifiers() - {"cmd"}):
            return True
        time.sleep(0.02)
    return False


def secure_input_active() -> bool:
    """True when macOS is blocking synthetic keystrokes (password field focused)."""
    try:
        import Quartz
        return bool(Quartz.IsSecureEventInputEnabled())
    except Exception:
        return False


def _send_paste_keystroke() -> tuple[bool, str]:
    """Synthesise ⌘V. Returns (ok, detail) — the return code is CHECKED."""
    try:
        import Quartz
        src = Quartz.CGEventSourceCreate(Quartz.kCGEventSourceStateHIDSystemState)
        V = 9   # kVK_ANSI_V
        for down in (True, False):
            ev = Quartz.CGEventCreateKeyboardEvent(src, V, down)
            Quartz.CGEventSetFlags(ev, Quartz.kCGEventFlagMaskCommand)
            Quartz.CGEventPost(Quartz.kCGHIDEventTap, ev)
            time.sleep(0.01)
        return True, "cgevent"
    except Exception as exc:
        # AppleScript fallback. Unlike the original, stderr is inspected:
        # System Events reports "not allowed assistive access" there while
        # still exiting 0 in some macOS versions.
        proc = subprocess.run(
            ["osascript", "-e",
             'tell application "System Events" to keystroke "v" using command down'],
            capture_output=True, text=True,
        )
        err = (proc.stderr or "").strip()
        if proc.returncode != 0 or err:
            return False, err or f"osascript exit {proc.returncode} ({exc})"
        return True, "osascript"


def press_enter() -> bool:
    """Press Return — for the trailing 'press enter' voice command."""
    try:
        import Quartz
        src = Quartz.CGEventSourceCreate(Quartz.kCGEventSourceStateHIDSystemState)
        for down in (True, False):
            ev = Quartz.CGEventCreateKeyboardEvent(src, 36, down)  # kVK_Return
            Quartz.CGEventPost(Quartz.kCGHIDEventTap, ev)
            time.sleep(0.01)
        return True
    except Exception:
        return False


def type_text(text: str) -> tuple[bool, str]:
    """Type the text directly as key events, bypassing the clipboard.

    Slower and it can't produce every character reliably, but it leaves the
    pasteboard completely untouched — the right choice when you're working
    with something valuable on the clipboard.
    """
    try:
        import Quartz
        src = Quartz.CGEventSourceCreate(Quartz.kCGEventSourceStateHIDSystemState)
        CHUNK = 20      # long strings in one event get truncated by some apps
        for i in range(0, len(text), CHUNK):
            piece = text[i:i + CHUNK]
            for down in (True, False):
                ev = Quartz.CGEventCreateKeyboardEvent(src, 0, down)
                Quartz.CGEventKeyboardSetUnicodeString(ev, len(piece), piece)
                Quartz.CGEventPost(Quartz.kCGHIDEventTap, ev)
            time.sleep(0.005)
        return True, "keystroke"
    except Exception as exc:
        return False, str(exc)


# ──────────────────────────────────────────────────────────────
# The public entry point
# ──────────────────────────────────────────────────────────────
def insert(text: str, cfg: dict, *, ctx=None) -> PasteResult:
    """Put `text` into the focused app. Serialised; never silently fails.

    On failure the text is deliberately LEFT on the clipboard and the old
    clipboard is not restored, so a ⌘V by hand still recovers the dictation.
    Losing a transcript is the one outcome worth trading anything to avoid.
    """
    if not text:
        return PasteResult(False, "none", "empty text")

    with _PASTE_LOCK:
        if cfg.get("paste_method") == "keystroke":
            ok, detail = type_text(text)
            return PasteResult(ok, "keystroke", detail)

        if secure_input_active():
            set_clipboard(text)
            return PasteResult(
                False, "clipboard-only",
                "macOS Secure Input is active (a password field has focus); "
                "the text is on your clipboard — press ⌘V")

        # A held ⌥ would turn ⌘V into ⌥⌘V. Wait briefly for you to let go.
        if not wait_for_modifiers_released():
            set_clipboard(text)
            return PasteResult(
                False, "clipboard-only",
                "a modifier key was still held, which would have changed the "
                "paste; the text is on your clipboard — press ⌘V")

        saved = snapshot_clipboard() if cfg.get("restore_clipboard", True) else None

        if not set_clipboard(text):
            return PasteResult(False, "clipboard", "could not write to the clipboard")

        # Confirm the write landed before synthesising the keystroke —
        # otherwise a failed copy pastes whatever was there before.
        if get_clipboard_text() != text:
            return PasteResult(False, "clipboard",
                               "clipboard did not accept the text")

        ok, detail = _send_paste_keystroke()
        if not ok:
            return PasteResult(
                False, "clipboard-only",
                f"could not send ⌘V ({detail}). Check System Settings → "
                f"Privacy & Security → Accessibility. The text is on your "
                f"clipboard — press ⌘V")

        # Restore scaled to the payload: a long paste genuinely takes longer
        # to land, and restoring too early makes the old clipboard get pasted
        # instead. Still a heuristic, but a proportionate one.
        if saved is not None:
            time.sleep(min(0.15 + len(text) / 4000.0, 1.0))
            restore_clipboard(saved)
        return PasteResult(True, "clipboard", detail)
